services:
  app:
    image: ${COMPOSE_PROJECT_NAME}:v0.1.0
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ${__project_path}:/app
      # todo: mount db volume for persistent storage
    command: ["sh", "/app/scripts/boot"]
    tty: true
    environment:
      GEMINI_API_KEY: /run/secrets/gemini_api_key
    secrets:
      - gemini_api_key

  db:
    image: postgres:16-alpine3.20
    command:
      ["postgres", "-c", "log_statement=mod", "-c", "log_destination=stderr"]
    restart: always
    ports:
      - 8001:5432
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_password

secrets:
  gemini_api_key:
    file: ./secrets/gemini_api_key.txt
  db_password:
    file: ./secrets/db_password.txt
