services:
  app:
    image: ${COMPOSE_PROJECT_NAME}:v0.1.0
    platform: linux/arm64
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    environment:
      DATABASE_URL_FILE: /run/secrets/db_url
    volumes:
      - ${__project_path}:/app
      # todo: mount db volume for persistent storage
    command: ["sh", "/app/scripts/boot"]
    tty: true
    secrets:
      - openai_api_key
      - db_url

  db:
    image: postgres:16-alpine3.20
    command:
      ["postgres", "-c", "log_statement=mod", "-c", "log_destination=stderr"]
    restart: always
    ports:
      - 8001:5432
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
      PGUSER: postgres
    secrets:
      - db_password
      - db_username
      - db_name

secrets:
  db_password:
    file: ./secrets/db/password.txt
  db_username:
    file: ./secrets/db/username.txt
  db_name:
    file: ./secrets/db/name.txt
  db_url:
    file: ./secrets/db/url.txt
  openai_api_key:
    file: ./secrets/openai/api_key.txt
