#!/bin/sh

# Clean up unused modules
npm prune

# temp workaround: Prisma only takes in entire database URL connection (why???)
# see https://github.com/prisma/prisma/discussions/12600
export DATABASE_URL=`cat $DATABASE_URL_FILE`

# Generate Prisma client, sync Prisma schema with db schema, and seed db
npx prisma generate
npx prisma db push
npx prisma db seed

# Format code on save 
npm run prettier-watch &

npm run dev

# Keep container alive indefinitely
tail -f /dev/null